[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.release]
# Reduce binary size
panic = "abort"
#strip = "symbols"
# Improve performance but increase compile time
#lto = "fat"
#codegen-units = 1

[dependencies]

egui = "0.20.1"
eframe = "0.20.1"
egui_extras = "0.20.0"

rand = "*"
num_cpus = "*"
nalgebra = "0.31.1"
parry3d = "0.12.0"
backtrace = "0.3"
image = "0.24.3"
chrono = "0.4"
tobj = "3.2.3"
serde_json = "1.0"
easy-gltf = "0.1.5"
attohttpc = "0.24.0"
bvh = "0.7.1"
regex = "1"