[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3

[profile.release]
# Reduce binary size
panic = "abort"
#strip = "symbols"
# Improve performance but increase compile time
#lto = "fat"
#codegen-units = 1

[dependencies]

#egui = "0.18.1"
#eframe = "0.18.0"
#egui_extras = "0.18.0"

#https://github.com/emilk/egui/discussions/1708
egui = { git = "https://github.com/emilk/egui"}
eframe = { git = "https://github.com/emilk/egui"}
egui_extras = { git = "https://github.com/emilk/egui"}

rand = "*"
num_cpus = "*"
nalgebra = "0.31.0"
parry3d = "0.9.0"
backtrace = "0.3"
image = "0.24.0"
chrono = "0.4"
tobj = "3.2.0"
serde_json = "1.0"
easy-gltf = "0.1.4"
attohttpc = "0.19.1"
bvh = "0.6.0"
regex = "1"